# 0x05-python-exceptions
Errors and Exceptions Handling using python tasks

## Task 0
Function: `def safe_print_list(my_list=[], x=0):` - prints `x` elements of a list.
 * File-name: `0-safe_print_list.py`.

## Task 1
Function: `def safe_print_integer(value):` - prints an integer.
* File-name: `1-safe_print_integer.py`.

## Task 2
Function: `def safe_print_list_integers(my_list=[], x=0):` - prints the first `x` elements of a list and only integers.
* File-name: `2-safe_print_list_integers.py`.

## Task 3
Function: `def safe_print_division(a, b):` - divides 2 integers and prints the result.
* File-name: `3-safe_print_division.py`.

## Task 4
Function: `def list_division(my_list_1, my_list_2, list_length):` - divides element by element in two lists.
* File-name: `4-list_division.py`.

## Task 5
Function: `def raise_exception():` - raises a type exception.
* File-name: `5-raise_exception.py`.

## Task 6
Functions: `def raise_exception_msg(message=""):` - raises a name exception with a message.
* File-name: `6-raise_exception_msg.py`.

# MANDATORY TASKS
Functions: `def safe_print_integer_err(value):` - prints an integer, with error message.
* File-name: `100-safe_print_integer_err.py`.
